// export const expenseCategories = [
//   {
//     id: '1',
//     name: 'Produkty spożywcze podstawowe',
//     description: 'chleb, jajka, mąka, cukier',
//   },
//   {
//     id: '2',
//     name: 'Mięso i ryby',
//     description: 'różne rodzaje mięs, wędliny, ryby i owoce morza',
//   },
//   { id: '3', name: 'Owoce', description: 'wszystkie rodzaje owoców' },
//   { id: '4', name: 'Warzywa', description: 'wszystkie rodzaje warzyw' },
//   { id: '5', name: 'Napoje', description: 'kawy, herbaty, soki, napoje gazowane' },
//   { id: '6', name: 'Alkohole', description: 'piwo, wódka, wino, whiskey' },
//   {
//     id: '7',
//     name: 'Słodycze i przekąski',
//     description: 'ciastka, czekolady, chipsy, orzechy',
//   },
//   {
//     id: '8',
//     name: 'Produkty zbożowe',
//     description: 'płatki śniadaniowe, kasze, ryż, makarony',
//   },
//   { id: '9', name: 'Nabiał', description: 'sery, mleko, jogurty, masło, śmietana' },
//   {
//     id: '10',
//     name: 'Dieta specjalna',
//     description: 'produkty bezglutenowe, wegańskie, dietetyczne',
//   },
//   {
//     id: '11',
//     name: 'Przyprawy i dodatki kuchenne',
//     description: 'oleje, sosy, przyprawy, zioła',
//   },
//   {
//     id: '12',
//     name: 'Gotowe dania i półprodukty',
//     description: 'zamrożone obiady, konserwy, gotowe sosy',
//   },
//   { id: '13', name: 'Mieszkanie', description: 'czynsz, opłaty mieszkania' },
//   { id: '14', name: 'Raty i kredyty', description: 'raty, kredyty, w tym hipoteczny' },
//   { id: '15', name: 'Media', description: 'opłaty za internet, telewizję, telefon' },
//   { id: '16', name: 'Energia', description: 'opłaty za zużycie prądu' },
//   { id: '17', name: 'Woda', description: 'opłaty za zużycie wody' },
//   { id: '18', name: 'Gaz', description: 'opłaty za zużycie gazu' },
//   { id: '19', name: 'Ogrzewanie domu', description: 'opłaty za ogrzewanie domu' },
//   {
//     id: '20',
//     name: 'Transport',
//     description: 'paliwo, bilety komunikacji miejskiej, bilet miesięczny',
//   },
//   {
//     id: '21',
//     name: 'Ubezpieczenia',
//     description: 'polisy zdrowotne, na życie, samochodowe',
//   },
//   { id: '22', name: 'Zdrowie', description: 'lekarstwa, wizyty lekarskie, zabiegi' },
//   { id: '23', name: 'Dzieci', description: 'opieka nad dziećmi, zabawki, ubrania' },
//   { id: '24', name: 'Odzież', description: 'ubrania, obuwie, akcesoria' },
//   {
//     id: '25',
//     name: 'Higiena osobista',
//     description: 'kosmetyki, fryzjer, salon kosmetyczny',
//   },
//   { id: '26', name: 'Rozrywka', description: 'kino, koncerty, imprezy' },
//   { id: '27', name: 'Urlop', description: 'podróże, noclegi, wycieczki' },
//   { id: '28', name: 'Restauracje i bary', description: 'jedzenie na mieście' },
//   { id: '29', name: 'Sport', description: 'siłownia, sprzęt sportowy, karnety' },
//   {
//     id: '30',
//     name: 'Zwierzęta domowe',
//     description: 'karma, wizyty u weterynarza, akcesoria',
//   },
//   { id: '31', name: 'Prezenty', description: 'urodziny, święta, inne okazje' },
//   {
//     id: '32',
//     name: 'Elektronika',
//     description: 'sprzęt RTV i AGD, komputery, smartfony',
//   },
//   { id: '33', name: 'Meble i wyposażenie', description: 'zakup nowych mebli' },
//   { id: '34', name: 'Kultura', description: 'muzea, teatr, wystawy' },
//   {
//     id: '35',
//     name: 'Edukacja i rozwój',
//     description: 'szkolenia, warsztaty, webinary, czesne, kursy',
//   },
//   { id: '36', name: 'Subskrypcje', description: 'serwisy streamingowe, czasopisma' },
//   {
//     id: '37',
//     name: 'Oszczędności',
//     description: 'regularne wpłaty na konto oszczędnościowe',
//   },
//   {
//     id: '38',
//     name: 'Inwestycje',
//     description: 'akcje, obligacje, fundusze inwestycyjne',
//   },
//   {
//     id: '39',
//     name: 'Podatki',
//     description: 'zaliczki na podatek dochodowy, inne opłaty publiczne',
//   },
//   {
//     id: '40',
//     name: 'Dary charytatywne',
//     description: 'wpłaty na rzecz organizacji charytatywnych',
//   },
//   { id: '41', name: 'Opłaty bankowe', description: 'prowizje, opłaty za kartę' },
//   { id: '42', name: 'Utrzymanie samochodu', description: 'przeglądy, naprawy' },
//   { id: '43', name: 'Hobby', description: 'materiały, akcesoria do hobby' },
//   { id: '44', name: 'Ogród', description: 'narzędzia, rośliny, meble ogrodowe' },
//   {
//     id: '45',
//     name: 'Utrzymanie domu',
//     description: 'naprawy, konserwacja, usługi fachowców',
//   },
//   {
//     id: '46',
//     name: 'Środki czystości',
//     description: 'detergenty, środki dezynfekujące, akcesoria do sprzątania',
//   },
//   {
//     id: '47',
//     name: 'Inne',
//     description: 'pozostałe wydatki, które nie pasują do żadnej z innych kategorii',
//   },
//   {
//     id: '48',
//     name: 'Książki i czasopisma',
//     description: 'zakup literatury fachowej i rozrywkowej',
//   },
//   {
//     id: '49',
//     name: 'Koszty prowadzenia działalności gospodarczej',
//     description: 'wydatki związane z prowadzeniem własnej firmy',
//   },
// ];

export const incomeCategories = [
  {
    id: '1',
    name: 'Wynagrodzenie',
    description: 'pensja, bonusy, prowizje od pracy etatowej',
  },
  {
    id: '2',
    name: 'Działalność gospodarcza',
    description: 'przychody z własnej firmy lub działalności freelance',
  },
  {
    id: '3',
    name: 'Inwestycje',
    description: 'dywidendy, zyski kapitałowe, przychody z najmu',
  },
  {
    id: '4',
    name: 'Renty i emerytury',
    description: 'przychody z tytułu renty, emerytury',
  },
  {
    id: '5',
    name: 'Wsparcie',
    description: 'regularne lub jednorazowe wsparcie finansowe',
  },
  { id: '6', name: 'Zwroty podatkowe', description: 'zwroty nadpłaconego podatku' },
  {
    id: '7',
    name: 'Stypendia',
    description: 'wsparcie finansowe na edukację, stypendia naukowe',
  },
  {
    id: '8',
    name: 'Nagrody i wygrane',
    description: 'pieniądze wygrane w konkursach, loteriach',
  },
  {
    id: '9',
    name: 'Sprzedaż osobista',
    description: 'przychody z sprzedaży używanych rzeczy, np. na aukcjach internetowych',
  },
  {
    id: '10',
    name: 'Inne przychody',
    description: 'inne sporadyczne lub nieregularne przychody',
  },
];
