name: GitHub Actions Vercel Production Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Format & Lint code
        uses: ./.github/actions/format-code

      - name: Build app
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_ENV: 'production'

      - name: Deploy app to Vercel production env
        uses: ./.github/actions/vercel-deployment
        with:
          mode: 'production'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          auth-secret: ${{secrets.NEXTAUTH_SECRET }}
          database-url: ${{ secrets.PROD_DATABASE_URL }}
          openai-key: ${{ secrets.API_KEY }}
          email-key: ${{ secrets.EMAIL_KEY }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_FORCE_NO_BUILD_CACHE: 1
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
          NEXT_ENV: 'production'
